# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

chunker <- function(seq_table, window_size = 20L) {
    .Call('_prider_chunker', PACKAGE = 'prider', seq_table, window_size)
}

make_degenerate_sequence <- function(sequences, sequence_length, cutoff = 0.1) {
    .Call('_prider_make_degenerate_sequence', PACKAGE = 'prider', sequences, sequence_length, cutoff)
}

process_blast_table <- function(filename, hit_len) {
    .Call('_prider_process_blast_table', PACKAGE = 'prider', filename, hit_len)
}

