# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
chunker <- function(seq_table, window_size = 20L) {
    .Call('_prider_chunker', PACKAGE = 'prider', seq_table, window_size)
}

group_primers <- function(primer_tbl) {
    .Call('_prider_group_primers', PACKAGE = 'prider', primer_tbl)
}

